[package]
name = "port_proxy"
version = "0.1.0"
authors = ["Sean Norris <sn76@st-andrews.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
